### ISSUE TITLE
邮件安全问题

### ISSUE THREAD

**Issue by delovt** [illacloud/builder-backend#58]
https://github.com/illacloud/builder-backend/blob/58aa74c271ec073edacf49408430de6f91595e46/pkg/smtp/service.go#L39

**Comment by delovt** [comment]
![截图_选择区域_20221125170440](https://user-images.githubusercontent.com/8826937/203945106-9a5a99b1-140f-4d8a-b50b-3cabdec61152.png)

**Comment by naj1n** [comment]
sry, did you run it with commented code?
